; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; В экосистеме PlatformIO понятия Platform (Платформа) и Framework (Фреймворк/Каркас) 
; отвечают за разные уровни разработки под микроконтроллеры (например, чип RP2040).
;
;  Разница между ними заключается в следующем:
;
;  1. Platform (Платформа) — «Аппаратная база»
;     Это пакет, который описывает сам микроконтроллер (или семейство чипов). 
;     Он содержит компилятор, средства прошивки (tools), базовые скрипты сборки 
;     и информацию о распределении памяти.
; 
;     Для RP2040: Это платформа Raspberry Pi RP2040.
;     За что отвечает: Позволяет PlatformIO понять, какое у вашего чипа "железо", 
;     как транслировать код в понятные для процессора инструкции (ARM Cortex-M0+) 
;     и как загружать готовую программу в память платы через USB или программатор.
;
;  2. Framework (Фреймворк) — «Программный фундамент»
;     Это набор готовых библиотек, API-функций и правил написания кода (скелет программы), 
;     который вы используете для управления периферией микроконтроллера. Фреймворк 
;     запускается поверх Платформы.
;
;     Для RP2040 в PlatformIO доступны:
;
;     Arduino: Самый популярный и простой вариант. Позволяет использовать привычные 
;              функции вроде digitalWrite(), библиотеки для датчиков и экранов.
;
;     Baremetal (Pico SDK): Официальный SDK от разработчиков Raspberry Pi на чистом C/C++. 
;              Дает максимальный контроль над регистрами и энергоэффективностью без лишних 
;              «накладных расходов».

[platformio]
default_envs = pico ; Окружение по умолчанию

; Параметры, общие для всех окружений (env)
[env]
board = pico
framework = arduino

; Параметры, характерные для окружения pico
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
; Параметр board_build.core в PlatformIO используется для выбора аппаратного ядра (core). 
; Он указывает компилятору, какую внутреннюю реализацию Arduino API и библиотек нужно 
; использовать для вашего микроконтроллера
board_build.core = earlephilhower
; Подключаемые библиотеки. Копируюся прямо в проект.
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	gyverlibs/GyverEncoder@^4.10
	greiman/SdFat@^2.3.1
; Скорость монитора COM-порта
monitor_speed = 115200
